name: Cypress Tests Run on Pipeline
run-name: GitHub Actions using Cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Npm install  
        run: npm install

      - name: Run Cypress
        run: npx cypress run
             
      - name: Upload artefatos screenshots
        uses: actions/upload-artifact@v4
            
        with:
          name: Cypress screenshots
          path: cypress/screenshots

      - name: Upload artefatos videos
        uses: actions/upload-artifact@v4
        with:
          name: Cypress videos
          path: cypress/videos
  